openapi: 3.0.0
info: 
  title: Delivery API
  version: 1.0.0
servers:
  - url: https://api.getjusto.com/api/v1
    description: Production server
tags:
  - name: Solicitudes de despacho externo
    description: Manejo de entregas y despachos externos
paths:
  /externo/{id}:
    post:
      tags:
       - Delivery
      security:
       - bearerAuth: []
      summary: Crear una solicitud de despacho externo
      description: Este endpoint permite crear una solicitud de despacho externo.
      parameters:
        - name: id
          in: path
          description: ID unico del despacho externo.
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
             $ref: '#/components/schemas/SolicitudExterno'
      responses:
        '200':
          description: Operacion existosa
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResultadoExterno'
        '401'
          $ref: '#/components/responses/unauthorizedError'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer 
      bearerFormat: JWT
  schemas:
    SolicitudExterno:
      type: string
      properties:
        storeId:
          type: number
          Description: ID del local
        instructions:
          type: string
          description: Instrucciones de entrega.
        externalId:
          type: string
          description: Código de idempotencia para identificar únicamente el pedido.
        tipAmount:
          type: number
          description: Monto de propina.
        originAddress:
          type: array
          description: Objeto que contiene la información del punto de origen del viaje.
          items:
            type: object
            properties:
              latitude:
                type: string
                description: Latitud de la dirección de entrega.
              longitude:
                type: string
                description: Longitud de la dirección de entrega.
              addressLine1:
                type: string
                description: Calle y número de la dirección de entrega.
              addressLine2:
                type: string
                description: Información adicional de la dirección de entrega.
              placePhone:
                type: string
                description: Teléfono del lugar de entrega (incluye código de país).
              placeName:
                type: string
                description: Nombre del lugar de entrega.
        destinationAddress:
          type: array
          description:  Objeto que contiene la información del punto de reparto. 
          items:
            type: object
            properties:
              latitude:
                type: string
                description: Latitud de la dirección de entrega.
              longitude:
                type: string
                description: Longitud de la dirección de entrega.
              addressLine1:
                type: string
                description: Calle y número de la dirección de entrega.
              addressLine2:
                type: string
                description: Información adicional de la dirección de entrega.
              placePhone:
                type: string
                description: Teléfono del lugar de entrega (incluye código de país).
              placeName:
                type: string
                description: Nombre del lugar de entrega.
        maxDistance: 
          type: number
          description: Distancia máxima permitida para calcular la ubicación.
        isRoundTrip: 
          type: boolean
          description: Indica si el reparto debe ser de ida y vuelta.
        requiredVehicleType: 
          type: string
          description: Definir el tipo de vehículo necesario para el delivery especial. 
        expectedDate:
          type: number
          description: Fecha de retiro en el primer punto.
        contents:
          type: array
          description: Lista de artículos incluidos en la entrega.
          items:
            type: object
            properties:
              name:
                type: string
                description: Nombre del producto.
              quantity:
                type: integer
                description: Cantidad del producto.
              description:
                type: string
                description: Descripción del producto.
              unitPrice:
                type: number
                description: Precio unitario del producto.
        avoidDuplication:
          type: boolean
          description: Activa el uso de ecternalId para evitar duplicados.
    ResultadoExterno:
      type: object
      properties:
        status:
          type: string
          description: Resultado de la operacion
        data:
          type: object
          description: Informacion sobre el despacho externo
          properties:
            delivery:
              type: number
              description: ID del despacho externo
  responses:
    unauthorizedError:
      description: Access token is missing or invalid
            