openapi: 3.0.0
info:
  title: Authentication API
  version: 1.0.0
servers:
  - url: https://api.getjusto.com/api/v1
    description: Production server
tags:
  - name: authentication
    description: Authentication related operations
paths:
  /me:
    get:
      tags:
        - authentication
      security:
        - bearerAuth: []
      summary: Get authentication data
      description: Use this endpoint to retrieve authentication data
      responses:
        '200':
          description: Authentication data retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: Operation result status
                  data:
                    type: object
                    properties:
                      userId:
                        type: string
                        description: Authenticated user ID
                      email:
                        type: string
                        description: User email
                      roles:
                        type: array
                        items:
                          type: string
                        description: User roles
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT




