openapi: 3.0.0
info:
  title: Client Endpoint API
  version: 1.0.0
servers:
  - url: https://api.getjusto.com/api/v2
    description: Production server
tags:
  - name: client
    description: Todo lo relacionado a operar con clientes
paths:
  /clients:
    get:
      tags:
        - client
      security:
        - bearerAuth: []
      responses:
        '200':
          description: success 
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/clientsResultGet'
  /clients/{id}:
    get:
      tags:
        - client
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          description: Corresponde al identificador del cliente.
          required: true
          schema:
            type: string
      responses:
        '200':
          description: success 
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/clientResultGet'
  /clients/addPoints:
    post:
      tags:
        - client
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - clientId
                - amount
              properties:
                clientId:
                  type: string
                  description: Identificador del cliente
                amount:
                  type: number
                  description: Cantidad de puntos a agregar
      responses:
        '200':
          description: success 
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: Resultado de la operación
                  data:
                    type: object
                    properties:
                      pointsBalance:
                        type: number
                        description: Nuevo saldo de puntos del cliente
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    clientsResultGet:
      type: object
      properties:
        totalPages:
          type: number
          description: Total de páginas
        totalCount:
          type: number
          description: Total de clientes
        hasNextPage:
          type: boolean
          description: Indica si hay una página siguiente
        hasPreviousPage:
          type: boolean
          description: Indica si hay una página anterior
        status:
          type: string
          description: Resultado de la operación.
        items:
          type: array
          items:
            $ref: '#/components/schemas/clientResultGet'

    clientResultGet:
      type: object
      properties:
        _id:
          type: string
          description: Identificador del cliente
        name:
          type: string
          description: Nombre del cliente
        email:  
          type: string
          description: Email del cliente
        phone:
          type: string
          description: Teléfono del cliente
        firstLogin:
          type: string
          description: Fecha de primer login
        lastLogin:
          type: string
          description: Fecha de último login
        ordersCount:
          type: number
          description: Cantidad de pedidos
        firstOrder:
          type: string
          format: date-time
          description: Fecha de primer pedido
        lastOrder:
          type: string
          format: date-time
          description: Fecha de último pedido
        pointsBalance:
          type: number
          description: Cantidad de puntos
        marketingEmailEnabled:
          type: boolean
          description: Indica si el cliente tiene habilitado el correo marketing
    
  responses:
    UnauthorizedError:
      description: Access token is missing or invalid
