openapi: 3.0.0
info:
  title: Client Endpoint API
  version: 1.0.0
servers:
  - url: https://api.getjusto.com/api/v2
    description: Production server
tags:
  - name: client
    description: Todo lo relacionado a operar con clientes
paths:
  /clients:
    get:
      tags:
        - client
      security:
        - bearerAuth: []
      responses:
        '200':
          description: success 
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: Resultado de la operación
                    example: ok
                  data:
                    type: object
                    $ref: '#/components/schemas/clientsResultGet'
        '400':
          description: Error en la petición
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: Resultado de la operación
                    example: error
                  error:
                    type: string
                    description: Mensaje de error
                    example: Error en la petición
        '401':
          description: Token inválido
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: Resultado de la operación
                    example: error
                  error:
                    type: string
                    description: Mensaje de error
                    example: Unauthorized
  /clients/{id}:
    get:
      tags:
        - client
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          description: Corresponde al identificador del cliente.
          required: true
          schema:
            type: string
      responses:
        '200':
          description: success 
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: Resultado de la operación
                    example: ok
                  data: 
                    type: object
                    $ref: '#/components/schemas/clientResultGet'
        '400':
          description: Error en la petición
          content:
            application/json:
              schema:
                type: object
                properties: 
                  status:
                    type: string
                    description: Resultado de la operación
                    example: error
                  error:
                    type: string  
                    description: Mensaje de error
                    example: Error en la petición
        '401':
          description: Token inválido
          content:
            application/json:
              schema: 
                type: object
                properties:
                  status:
                    type: string
                    description: Resultado de la operación
                    example: error  
                  error:
                    type: string
                    description: Mensaje de error
                    example: Unauthorized 
  /clients/addPoints:
    post:
      tags:
        - client
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - clientId
                - amount
              properties:
                clientId:
                  type: string
                  description: Identificador del cliente
                amount:
                  type: number
                  description: Cantidad de puntos a agregar
      responses:
        '200':
          description: success 
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/addPointsResult'
        '400':
          description: Error en la petición
          content:
            application/json:
              schema:
                type: object
                properties: 
                  status:
                    type: string
                    description: Resultado de la operación
                    example: error
                  error:
                    type: string  
                    description: Mensaje de error
                    example: Error en la petición
        '401':
          description: Token inválido
          content:
            application/json:
              schema: 
                type: object
                properties:
                  status:
                    type: string
                    description: Resultado de la operación
                    example: error  
                  error:
                    type: string
                    description: Mensaje de error
                    example: Unauthorized 
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    clientsResultGet:
      type: object
      properties:
        totalPages:
          type: number
          description: Total de páginas
        totalCount:
          type: number
          description: Total de clientes
        hasNextPage:
          type: boolean
          description: Indica si hay una página siguiente
        hasPreviousPage:
          type: boolean
          description: Indica si hay una página anterior
        status:
          type: string
          description: Resultado de la operación.
        items:
          type: array
          items:
            $ref: '#/components/schemas/clientResultGet'
    clientResultGet:
      type: object
      properties:
        _id:
          type: string
          description: Identificador del cliente
        name:
          type: string
          description: Nombre del cliente
        email:  
          type: string
          description: Email del cliente
        phone:
          type: string
          description: Teléfono del cliente
        firstLogin:
          type: string
          description: Fecha de primer login
        lastLogin:
          type: string
          description: Fecha de último login
        ordersCount:
          type: number
          description: Cantidad de pedidos
        firstOrder:
          type: string
          format: date-time
          description: Fecha de primer pedido
        lastOrder:
          type: string
          format: date-time
          description: Fecha de último pedido
        pointsBalance:
          type: number
          description: Cantidad de puntos
        marketingEmailEnabled:
          type: boolean
          description: Indica si el cliente tiene habilitado el correo marketing 
    addPointsResult:
      type: object
      properties:
        status:
          type: string
          description: Resultado de la operación
          example: ok
        data: 
          type: object
          properties:
            amount:
              type: number
              description: Cantidad de puntos agregados
              example: 1000
            websiteId:
              type: string
              description: Identificador del sitio web
              example: ErCkmcyCEovseJq5E
            date:
              type: string
              format: date-time
              description: Fecha de la operación  
              example: 2022-03-01T13:18:59.381Z
            balance:
              type: number
              description: Cantidad de puntos agregados
              example: 5026
            user:
              type: object
              properties:
                clientId:
                  type: string
                  description: Identificador del cliente
                  example: YdhZfJzvD2atjXeED
                email:
                  type: string
                  description: Email del cliente
                  example: jdoe@gmail.com
                fullName:
                  type: string
                  description: Nombre del cliente
                  example: John  Doe
                phone:
                  type: string
                  description: Teléfono del cliente
                  example: "+56912345678"
