openapi: 3.0.0
info:
  title: Stores Endpoint API
  version: 1.0.0
servers:
  - url: https://api.getjusto.com/api/v2
    description: Production server
tags:
  - name: store
    description: Todo lo relacionado a operar con locales
paths:
  /stores:
    get:
      tags:
        - store
      security:
        - bearerAuth: []
      summary: Obtener locales
      description: Obtiene todos los locales de la marca  
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/storeResult'
    patch:
      tags:
        - store
      security:
        - bearerAuth: []
      summary: Actualizar local
      description: Actualiza la información de un local específico  
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                storeId:
                  type: string
                name:
                  type: string
                acceptDelivery:
                  type: boolean
                acceptGo:
                  type: boolean
                acceptServe:
                  type: boolean
                externalId:
                  type: string 
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: Resultado de la operación
                    example: ok 
                  data:
                    $ref: '#/components/schemas/storeResult'  
  /stores/{id}:
    get:
      tags:
        - store
      security:
        - bearerAuth: []
      summary: Obtener local
      description: Obtiene la información de un local específico
      parameters:
        - name: id
          in: path
          required: true
          schema:   
            type: string
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: Resultado de la operación
                    example: ok
                  data: 
                    $ref: '#/components/schemas/storeResult'
  /stores/{id}/schedule:
    patch:
      tags:
        - store
      security:
        - bearerAuth: []
      summary: Actualizar horarios
      description: Actualiza los horarios de un local específico  
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/scheduleSchema'
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: Resultado de la operación
                    example: ok 
                  data:
                    $ref: '#/components/schemas/storeResult'
  /stores/{id}/temporaryCloseStore:
    patch:
      tags:
        - store
      security:
        - bearerAuth: []
      summary: Cierre temporal del local
      description: Cierra temporalmente un local
      requestBody:
        required: true
        content:
          application/json:
            schema: 
              type: object
              properties:
                closedUntilDate:
                  type: string
                  format: date-time
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: Resultado de la operación
                    example: ok 
                  data:
                    $ref: '#/components/schemas/storeResult'
  /stores/{id}/currentPreparationDuration:
    patch:
      tags:
        - store
      security:
        - bearerAuth: []  
      summary: Actualizar tiempo de preparación
      description: Actualiza el tiempo de preparación de un local
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            description: ID del local
      requestBody:
        required: true
        content:
          application/json:
            schema: 
              type: object
              properties:
                currentPreparationDuration:
                  type: number
                  description: Tiempo de preparación en minutos.
                  example: 10
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: Resultado de la operación
                    example: ok
                  data:
                    $ref: '#/components/schemas/storeResult'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    storeResult:
      type: object
      properties: 
        _id:
          type: string
          description: ID del local.
          example: xKoiiqdtKGaRA2ve4
        externalId:
          type: string
          description: ID externo indicado en la información del local.
          example: 2345
        websiteId:
          type: string
          description: ID de la marca.
          example: ErCkmcyCEovseJq5E
        name:
          type: string
          description: Nombre del local.
          example: Peña
        acceptDelivery:
          type: boolean
          description: Si es que acepta pedidos por delivery.
          example: true
        acceptServe:
          type: boolean
          description: Si es que acepta pedidos para servir en el local.
          example: true
        acceptGo:
          type: boolean
          description: Si es que acepta pedidos para llevar.
          example: true
        currentPreparationDuration:
          type: number
          description: Tiempo actualiza de preparación (sólo cocina) en minutos.
          example: 10
        phone:
          type: string
          description: Teléfono del local.
          example: "null"
        address:
          type: object
          description: Dirección del local.
          properties:
            placeId:
              type: string
              description: Place ID de Google Maps
              example: EihBdmVuaWRhIEhvbGFuZGEgMTYwNSwgUHJvdmlkZW5jaWEsIENoaWxlIjESLwoUChIJCfBr63TPYpYRguPJ8LiSNSgQxQwqFAoSCbELmxJ1z2KWEdvDHqTQ
            address:
              type: string
              description: Calle y número.
              example: Avenida Holanda 1605
            addressLine2:
              type: number 
              description: Número del departamento.
              example: 1234
            addressSecondary:
              type: string
              description: Localidad.
              example: Providencia, Chile
            comment:
              type: string
              description: Comentarios.
              example: Dejar con el conserje
            location:
              type: object
              description: Latitud y longitud.
              properties:
                lat:
                  type: number
                  description: Latitud.
                  example: -33.4334297
                lng:
                  type: number
                  description: Longitud.
                  example: -70.59966380000002
        schedule:
          type: object
          description: Información de horarios del local.
          properties:
            closedUntilDate:
              type: string
              format: date-time
              description: Fecha en la que vuelve a estar disponible. (Solo si es que esta cerrado temporalmente)
              example: "null"
            closedDays:
              type: array
              description: Fechas exactas cuando esta cerrado (como feriados).
              items:
                type: string
                format: date-time
            availableAtPeriods:
              type: boolean
              description: Si es que es verdadero, se usan periodos de apertura. Si que es falso, esta disponible siempre.
              example: false
            openPeriods:
              type: array
              description: Un arreglo con los periodos de apertura.
              items:
                type: object
                properties:
                  daysOfWeek:
                    type: array
                    description:  Un arreglo con los días de la semana en que este periodo aplica. Lunes es 1 y domingo es 7.
                    items:
                      type: number
                    example: [1, 2, 3, 4, 5, 6, 7]
                  fromMinute:
                    type: number
                    description: Minutos desde las 12 de la mañana en que empieza este periodo.
                    example: 480
                  toMinute:
                    type: number
                    description: Minutos desde las 12 de la mañana en que termina este periodo.
                    example: 1200
            timezone:
              type: string
              description: Zona horaria.
              example: America/Santiago
    scheduleSchema:
      type: object
      properties:
        schedule:
          type: object
          properties:
            closedDays:
              type: array
              description: Fechas exactas cuando esta cerrado (como feriados).
              items:
                type: string
                format: date-time
            openPeriods:
              type: array
              description: Un arreglo con los periodos de apertura.
              items:
                type: object
                properties:
                  daysOfWeek:
                    type: array
                    description:  Un arreglo con los días de la semana en que este periodo aplica. Lunes es 1 y domingo es 7.
                    items:
                      type: number
                      example: [1, 2, 3, 4, 5, 6, 7]
                  fromMinute:
                    type: number
                    description: Minutos desde las 12 de la mañana en que empieza este periodo.
                    example: 480
                  toMinute:
                    type: number
                    description: Minutos desde las 12 de la mañana en que termina este periodo.
                    example: 1200